# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: utils/service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'utils/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13utils/service.proto\x12\x0fmessage_service\"\x11\n\x0fRegisterRequest\"%\n\x10RegisterResponse\x12\x11\n\tclient_id\x18\x01 \x01(\t\"!\n\x0eMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"$\n\x0fMessageResponse\x12\x11\n\tresponses\x18\x01 \x03(\t2\xb3\x01\n\x0eMessageService\x12P\n\x0bSendMessage\x12\x1f.message_service.MessageRequest\x1a .message_service.MessageResponse\x12O\n\x08Register\x12 .message_service.RegisterRequest\x1a!.message_service.RegisterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=40
  _globals['_REGISTERREQUEST']._serialized_end=57
  _globals['_REGISTERRESPONSE']._serialized_start=59
  _globals['_REGISTERRESPONSE']._serialized_end=96
  _globals['_MESSAGEREQUEST']._serialized_start=98
  _globals['_MESSAGEREQUEST']._serialized_end=131
  _globals['_MESSAGERESPONSE']._serialized_start=133
  _globals['_MESSAGERESPONSE']._serialized_end=169
  _globals['_MESSAGESERVICE']._serialized_start=172
  _globals['_MESSAGESERVICE']._serialized_end=351
# @@protoc_insertion_point(module_scope)
